parameters:
    locale: "%env(LOCALE)%"
    router.request_context.host: "%env(DEVLIVER_HOST)%"
    router.request_context.scheme: "%env(DEVLIVER_SCHEME)%"
    router.request_context.base_url: "%env(DEVLIVER_BASE_URL)%"
        
    devliver_dir:           '%kernel.project_dir%/var/devliver'
    version_file:           '%kernel.project_dir%/version'

    devliver_package_dir:   '%devliver_dir%/package'
    devliver_dist_dir:      '%devliver_dir%/dist'
    devliver_composer_dir:  '%devliver_dir%/composer'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $composerDirectory: '%devliver_composer_dir%'
            $distDir: '%devliver_dist_dir%'
            $versionFile: '%version_file%'
            $projectDir: '%kernel.project_dir%'
            Symfony\Component\Cache\Adapter\TagAwareAdapterInterface: '@cache.tag.app'

    _instanceof:
        Doctrine\Common\EventSubscriber:
            tags: ['doctrine.event_subscriber']

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Model,Migrations,Tests,Kernel.php,bootstrap.php}'
        
    Cocur\Slugify\Slugify: ~

    cache.tag.app:
        class: Symfony\Component\Cache\Adapter\TagAwareAdapter
        decorates: cache.app
        arguments: ['@cache.tag.app.inner']

    # controller
    App\Controller\:
        resource: '../src/Controller/*'
        tags: ['controller.service_arguments']

    devliver.main_menu_left:
        class: Knp\Menu\MenuItem
        factory: ['@App\Menu\Builder', mainMenu]
        tags:
            - { name: knp_menu.menu, alias: main_left }

    devliver.main_menu_right:
        class: Knp\Menu\MenuItem
        factory: ['@App\Menu\Builder', rightNavbar]
        tags:
            - { name: knp_menu.menu, alias: main_right }

    devliver.security.token_authenticator: '@App\Security\TokenAuthenticator'
    devliver.security.api_token_user_provider: '@App\Security\ApiTokenUserProvider'
    devliver.security.repository_token_user_provider: '@App\Security\RepositoryTokenUserProvider'
